name: publish to Reposilite

on:
  release:
    types: [ published ]

jobs:
  publish_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set version
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed "s/^v//")" >> $GITHUB_ENV
          echo "refs: ${{ github.ref }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      # Set up Gradle
      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper

      - name: Gradle Build and publish to Reposilite
        run: ./gradlew build publish -Pversion=${{ env.RELEASE_VERSION }}
        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}